version: 2
sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: axial-trail-485514-p5
    schema: nytaxi
    tables:
      - name: yellow_tripdata
      - name: green_tripdata